### ISSUE TITLE
select codec to dump

### ISSUE THREAD

**Issue by roddy20** [Goldfish64/AudioPkg#2]
HdaCodecDump start
Codec: NVIDIA (Unknown)
AFG Function Id: 0x1 (unsol 0)
Vendor ID: 0x10DE0042
Revision ID: 0x100100
Default PCM: N/A
Default Amp-In caps: N/A
Default Amp-Out caps: N/A
.......
it works but I need a dump of Analog Codec,  not HDMI
how to fix that?

**Comment by roddy20** [comment]
HdaCodecHandles[1] works
Codec: Analog Devices AD1988B
AFG Function Id: 0x1 (unsol 0)
Vendor ID: 0x11D4198B
Revision ID: 0x100400
Default PCM:
    rates [0x7FF]: 8000 11025 16000 22050 32000 44100 48000 88200 96000 176400 192000
    bits [0xE]: 16 20 24
    formats [0x1]: PCM
Default Amp-In caps: ofs=0x00, nsteps=0x00, stepsize=0x mute=0
Default Amp-Out caps: ofs=0x27, nsteps=0x27, stepsize=0x mute=5
Node 0x02 [Audio Output] wcaps 0x30311: Stereo Digital

**Comment by roddy20** [comment]
for (UINTN i = 0; i < HdaCodecHandleCount; i++)
    {
.....
}
    return EFI_SUCCESS;
    }

**Comment by Goldfish64** [comment]
Yeah that application's code is still mostly test code from earlier in development. I'll get around to cleaning it up in time

**Comment by roddy20** [comment]
after this change it works OK both with Codec and HDMI
it is a great idea to make HDAdump independent of Linux, Windows, Codec Commander, VoodooHDA etc
Thanks and happy holidays!
