### ISSUE TITLE
ALC256 not supported

### ISSUE THREAD

**Issue by ellaosx2007** [Goldfish64/AudioPkg#4]
Hdacodecdump shows nothing. I grab codec from ubuntu. Hope it helps to solve the issue.
[codec_dump.txt](https://github.com/Goldfish64/AudioPkg/files/2739851/codec_dump.txt)
![20190109_151739](https://user-images.githubusercontent.com/44796541/50885670-55f75d00-1429-11e9-94e1-23b2e30ceecf.jpg)

**Comment by Goldfish64** [comment]
You need the AudioDxe driver loaded.

**Comment by ellaosx2007** [comment]
I have it loaded, both audiodxe & boootchimedxe in drivera64uefi folder. My other computers are working fine with your efi files

**Comment by Goldfish64** [comment]
Please post the output of the `devices` command. You can pipe the output to a file by doing `devices > devices.txt`

**Comment by ellaosx2007** [comment]
Here it is...
[devices.txt](https://github.com/Goldfish64/AudioPkg/files/2743549/devices.txt)

**Comment by Goldfish64** [comment]
Hmm it's not listed in that output. Does the driver show up if you run the command `drivers`? There should be a `HDA Controller Driver` and `HDA Codec Driver` listed.

**Comment by ellaosx2007** [comment]
Thats what i thought so, bht it doesnt show up. It only shows in linux

**Comment by ellaosx2007** [comment]
Il try drivers.. be back in 30min

**Comment by ellaosx2007** [comment]
Here...
[drivers.txt](https://github.com/Goldfish64/AudioPkg/files/2743629/drivers.txt)

**Comment by Goldfish64** [comment]
The drivers are definitely loaded then, loading debug builds of the drivers may reveal the culprit. What motherboard/system are you on?

**Comment by ellaosx2007** [comment]
Acer Swift 3 SF314-54. Running High Sierra with latest clover. Speaker & headphone works, except for the microphone.
How can i get the debug build?

**Comment by Goldfish64** [comment]
[Debug.zip](https://github.com/Goldfish64/AudioPkg/files/2743672/Debug.zip)

You will likely need to load them manually by removing the current ones from drivers64UEFI, going into the shell, and running `load DRIVER` where `DRIVER` is the path to the debug build of AudioDxe.efi. You should see a bunch of output as the driver loads.

**Comment by ellaosx2007** [comment]
oh ok. So i will compile as debug? il be back as soon i have run it.
Thank you :)

**Comment by Goldfish64** [comment]
The compiled binaries are attached to my previous comment.

**Comment by ellaosx2007** [comment]
Hi Goldfish64
Il get back to you this week. The laptop is at home.
Thank you
