### ISSUE TITLE
default volume

### ISSUE THREAD

**Issue by Sher1ocks** [Goldfish64/AudioPkg#5]
hello first of all, thank you for your project.
i can use BootChimeCfg.efi on modern system(UEFI). but old firmware(UEFI). ex HP 4320s laptop(sandy bridge). I can't access shell. as result, i can't command BootChimeCfg.efi option.
always play Boot sound with full volume.
can i decrease boot sound volume?

**Comment by Goldfish64** [comment]
Older firmware can likely use a v1 shell, although the application itself has issues with older firmware. I may change the driver to use the NVRAM variable that real Macs use for boot chime by default instead of simply using max volume.

**Comment by Goldfish64** [comment]
Converted the application to be interactive and remove the dependencies on ShellPkg which seem to have additional dependencies that don't exist on older UEFI revisions. You should be able to add the BootChimeCfg.efi application as a custom tool to Clover and run it from there. You can then change the device/volume as you see fit.
